### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by MGuruNikhil** [flemingslefthandrule/cityvoicejs#3]
- [x] local feed rendering error (infinite requests r going to /posts/localfeed endpoint)
- [ ] following feed rendering (backend too)
- [ ] send posts in reverse order at user/username/posts end point
- [x] rendering followers list and following list in the profile component
- [ ] making upvote, downvote, comment functional
- [ ] rendering labels and tags
- [ ] rendering polls, results
- [ ] creating fullPost component ( middle component is entirely filled with a single selected post and its comment section )
- [ ] send replies of a post in response at post/postid end point
- [ ] explore page
- [ ] redirecting to explore page when a user searched for something on rhs search bar and clicks on the link saying "search for posts/polls"
- [ ] adding profile pic to the user model and handling upload profile pic in front end
- [ ] profile edit page
- [ ]  adding media to the post while creating post
- [ ] rendering media added to a post / poll
- [ ] geotag
- [ ] creating multiple servers, connecting them and rendering global feed and more decentralized stuff 
@aquaticcalf  @jagadeesh-debug  @Nischa1Mv  @Nischal-18

**Comment by aquaticcalf** [comment]
issue too long, i am going to close this now and make smaller issues addressing each todo. thatd make it easier for discussing and distributing work.
